import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";
import NavList from "@/components/nav-list";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn(
                "min-h-screen font-sans antialiased",
                fontSans.variable
            )}>
                <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem={true}
                >
                    <div className="w-full sticky top-0">
                        <nav className="w-full max-w-5xl mx-auto px-6 h-20 flex items-center justify-between">
                            <Link href="/" className="text-2xl font-bold text-foreground">Video tools</Link>
                            <NavList />
                        </nav>
                    </div>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}